---
title: "Lab 06"
author: "Otobo Ujah"
date: "2/24/2022"
output: html_document
---

```{r}
library(tidyverse)

songs <- read.csv("https://raw.githubusercontent.com/bwiernik/progdata-class/master/data/singer/songs.csv")
locations <- read.csv("https://raw.githubusercontent.com/bwiernik/progdata-class/master/data/singer/loc.csv")

(time <- as_tibble(songs) |> rename(song = title))

(album <- as_tibble(locations) |> 
    select(title, everything()) |> 
    rename(album = release,
           song  = title))
```

### Exercise 1

#1. 
```{r}


time |> left_join(album , by = c("song","artist_name"))

```

#2. 
```{r}
time |> full_join(album , by = c("song","artist_name"))

```

#3. 
```{r}
time |> anti_join(album , by = "song")

```
#4.
```{r}
time |> anti_join(album , by = "artist_name")

```

#5.
```{r}
time |> full_join(album , by = "song")
```


### Exercise 2: LOTR

```{r}

fell <- read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/The_Fellowship_Of_The_Ring.csv")

ttow <- read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/The_Two_Towers.csv")

retk <- read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/The_Return_Of_The_King.csv")
```

1. Stack data frames into a single tibble
```{r}
bind_rows(fell, ttow, retk)
```

2. Races in Fellowship of the Ring but not in the other data frame

```{r}
fell |> 
  anti_join(ttow, by = "Race") |> 
  anti_join(retk, by = "Race")
```


### Exercise 3: Set Operations

```{r}
(y <-  tibble(x1 = LETTERS[1:3], x2 = 1:3))

(z <- tibble(x1 = c("B", "C", "D"), x2 = 2:4))
```

1. Rows in both y and z

```{r}

intersect(y, z)
```

2. Reflect data y collected on day 1 and z on day 2

```{r}
union(
  mutate(y, day = "Day 1"),
  mutate(z, day = "Day 2")
)

```

3. Removing bad rows in z from y

```{r}

setdiff(y,z)
```

