---
title: "Lab 3"
author: "Otobo Ujah"
date: "2/15/2022"
output:
  pdf_document: default
  html_document: default
---


Ex 1.0: Loading libraries



```{r}
library(tidyverse)
library(gapminder)
```


Ex 1.1 : Three countries in 1970's

```{r}
gapminder |> 
  filter(country == "Nigeria"| country == "Ghana"| country == "Senegal") |> 
  filter(year >= 1970 & year <=1979)
  
```


Ex 1.2 : Three countries in 1970's with respective GDP Per Capita

```{r}

gapminder |> filter(country == "Nigeria"| country == "Ghana"| country == "Senegal") |> 
  filter(year >= 1970 & year <=1979) |>
  select(country, gdpPercap)

```



Ex 1.3: Changes in life expectancy by country


```{r}
lifechanged <-  gapminder|> 
  arrange(country) |>
  mutate(lifeChange = lifeExp - lag(lifeExp))  |> filter(lifeChange < 0)
```



Ex 1.4: Maximum GDP per capita experienced by each country


```{r}
gapminder |> 
  arrange(country) |> 
  group_by(country) |> 
  filter(gdpPercap==max(gdpPercap))

```


Ex 1.5 Scatterplot of Canada's life expectance vs GDP Per Capita



```{r}
gapminder |>filter(country=="Canada") |>
  ggplot(aes(y = lifeExp, x = gdpPercap, size = gdpPercap)) +
  geom_point() +
  scale_x_continuous(
    name = "GDP per capita", 
    trans = "log10", 
    labels = scales::dollar_format()) +
  labs(y = "Life Expectancy", 
       title = "Scatterplot of Life Expectancy and GDP Per Capita for Canada")
```


Ex 2.1 Exploring Palmerpenguins using dplyr and ggplot


```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(palmerpenguins)

penguins |> 
  group_by(species) |> 
  summarise(bill_length_mean = mean(bill_length_mm, na.rm = T),
            body_mass_mean = mean(body_mass_g, na.rm = T),
            bill_length_sd = sd(bill_length_mm, na.rm = T),
            body_mass_sd = sd(body_mass_g, na.rm = T)) 

penguins |> ggplot(aes( x =  body_mass_g, y=  bill_length_mm)) +
  geom_point(aes(color =species))+
  geom_smooth() +
  labs(x = "Body mass",
       y = "Bill length",
       title = "Scatterplot of Body mass and Bill length for Penguins")
```

